package model;
// Generated Aug 27, 2019 8:54:45 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassCredit generated by hbm2java
 */
@Entity
@Table(name = "class_credit", catalog = "qlsv")
public class ClassCredit implements java.io.Serializable {

	private Integer id;
	private String name;
	private String note;
	private Set<ClassSubject> classSubjects = new HashSet<ClassSubject>(0);

	public ClassCredit() {
	}

	public ClassCredit(String name, String note, Set<ClassSubject> classSubjects) {
		this.name = name;
		this.note = note;
		this.classSubjects = classSubjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classCredit")
	public Set<ClassSubject> getClassSubjects() {
		return this.classSubjects;
	}

	public void setClassSubjects(Set<ClassSubject> classSubjects) {
		this.classSubjects = classSubjects;
	}

}
