package model;
// Generated Aug 26, 2019 9:59:05 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassSubject generated by hbm2java
 */
@Entity
@Table(name = "class_subject", catalog = "qlsv")
public class ClassSubject implements java.io.Serializable {

	private Integer id;
	private ClassCredit classCredit;
	private Subjects subjects;
	private String startTime;
	private String endTime;
	private String note;
	private Set<Registersub> registersubs = new HashSet<Registersub>(0);
	private Set<StudentsSubjects> studentsSubjectses = new HashSet<StudentsSubjects>(0);

	public ClassSubject() {
	}

	public ClassSubject(ClassCredit classCredit, Subjects subjects, String startTime, String endTime, String note,
			Set<Registersub> registersubs, Set<StudentsSubjects> studentsSubjectses) {
		this.classCredit = classCredit;
		this.subjects = subjects;
		this.startTime = startTime;
		this.endTime = endTime;
		this.note = note;
		this.registersubs = registersubs;
		this.studentsSubjectses = studentsSubjectses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id")
	public ClassCredit getClassCredit() {
		return this.classCredit;
	}

	public void setClassCredit(ClassCredit classCredit) {
		this.classCredit = classCredit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id")
	public Subjects getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Subjects subjects) {
		this.subjects = subjects;
	}

	@Column(name = "start_time", length = 65535)
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_time", length = 65535)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classSubject")
	public Set<Registersub> getRegistersubs() {
		return this.registersubs;
	}

	public void setRegistersubs(Set<Registersub> registersubs) {
		this.registersubs = registersubs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classSubject")
	public Set<StudentsSubjects> getStudentsSubjectses() {
		return this.studentsSubjectses;
	}

	public void setStudentsSubjectses(Set<StudentsSubjects> studentsSubjectses) {
		this.studentsSubjectses = studentsSubjectses;
	}

}
