package model;
// Generated Aug 26, 2019 9:59:05 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name = "classes", catalog = "qlsv", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Classes implements java.io.Serializable {

	private Integer id;
	private String name;
	private String code;
	private Set<Students> studentses = new HashSet<Students>(0);

	public Classes() {
	}

	public Classes(String name, String code) {
		this.name = name;
		this.code = code;
	}

	public Classes(String name, String code, Set<Students> studentses) {
		this.name = name;
		this.code = code;
		this.studentses = studentses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", unique = true, nullable = false, length = 6)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "classes")
	public Set<Students> getStudentses() {
		return this.studentses;
	}

	public void setStudentses(Set<Students> studentses) {
		this.studentses = studentses;
	}

}
