package model;
// Generated Aug 27, 2019 8:54:45 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ClassPayroll generated by hbm2java
 */
@Entity
@Table(name = "class_payroll", catalog = "qlsv", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class ClassPayroll implements java.io.Serializable {

	private Integer id;
	private String name;
	private String code;
	private Set<Student> students = new HashSet<Student>(0);

	public ClassPayroll() {
	}

	public ClassPayroll(String name, String code) {
		this.name = name;
		this.code = code;
	}

	public ClassPayroll(String name, String code, Set<Student> students) {
		this.name = name;
		this.code = code;
		this.students = students;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", unique = true, nullable = false, length = 6)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classPayroll")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
