package model;
// Generated Aug 27, 2019 2:14:58 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClassSubject generated by hbm2java
 */
@Entity
@Table(name = "class_subject", catalog = "qlsv")
public class ClassSubject implements java.io.Serializable {

	private Integer id;
	private ClassCredit classCredit;
	private Subject subject;
	private Date startTime;
	private Date endTime;
	private String day;
	private Date todStart;
	private Date todEnd;
	private String note;
	private Integer size;
	private Integer registered;
	private Set<Registersub> registersubs = new HashSet<Registersub>(0);

	public ClassSubject() {
	}

	public ClassSubject(ClassCredit classCredit, Subject subject, Date startTime, Date endTime, String day,
			Date todStart, Date todEnd, String note, Integer size, Integer registered, Set<Registersub> registersubs) {
		this.classCredit = classCredit;
		this.subject = subject;
		this.startTime = startTime;
		this.endTime = endTime;
		this.day = day;
		this.todStart = todStart;
		this.todEnd = todEnd;
		this.note = note;
		this.size = size;
		this.registered = registered;
		this.registersubs = registersubs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "class_id")
	public ClassCredit getClassCredit() {
		return this.classCredit;
	}

	public void setClassCredit(ClassCredit classCredit) {
		this.classCredit = classCredit;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "subject_id")
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_time", length = 10)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_time", length = 10)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "day", length = 65535)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tod_start", length = 16)
	public Date getTodStart() {
		return this.todStart;
	}

	public void setTodStart(Date todStart) {
		this.todStart = todStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tod_end", length = 16)
	public Date getTodEnd() {
		return this.todEnd;
	}

	public void setTodEnd(Date todEnd) {
		this.todEnd = todEnd;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "size")
	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	@Column(name = "registered")
	public Integer getRegistered() {
		return this.registered;
	}

	public void setRegistered(Integer registered) {
		this.registered = registered;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "classSubject")
	public Set<Registersub> getRegistersubs() {
		return this.registersubs;
	}

	public void setRegistersubs(Set<Registersub> registersubs) {
		this.registersubs = registersubs;
	}

	@Override
	public String toString() {
		return "ClassSubject{" +
				"id=" + id +
				", classCredit=" + classCredit +
				", subject=" + subject +
				", startTime=" + startTime +
				", endTime=" + endTime +
				", day='" + day + '\'' +
				", todStart=" + todStart +
				", todEnd=" + todEnd +
				", note='" + note + '\'' +
				", size=" + size +
				", registered=" + registered +
				'}';
	}
}
