package model;
// Generated Aug 27, 2019 2:14:58 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name = "province", catalog = "qlsv")
public class Province implements java.io.Serializable {

	private String id;
	private String name;
	private String type;
	private Set<District> districts = new HashSet<District>(0);

	public Province() {
	}

	public Province(String id, String name, String type) {
		this.id = id;
		this.name = name;
		this.type = type;
	}

	public Province(String id, String name, String type, Set<District> districts) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.districts = districts;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 6)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "province")
	public Set<District> getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set<District> districts) {
		this.districts = districts;
	}

}
