package model;
// Generated Aug 26, 2019 9:59:05 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Registersub generated by hbm2java
 */
@Entity
@Table(name = "registersub", catalog = "qlsv")
public class Registersub implements java.io.Serializable {

	private Integer id;
	private ClassSubject classSubject;
	private Students students;
	private Timedayonweek timedayonweek;

	public Registersub() {
	}

	public Registersub(ClassSubject classSubject, Students students, Timedayonweek timedayonweek) {
		this.classSubject = classSubject;
		this.students = students;
		this.timedayonweek = timedayonweek;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_sub_id")
	public ClassSubject getClassSubject() {
		return this.classSubject;
	}

	public void setClassSubject(ClassSubject classSubject) {
		this.classSubject = classSubject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tdow_id")
	public Timedayonweek getTimedayonweek() {
		return this.timedayonweek;
	}

	public void setTimedayonweek(Timedayonweek timedayonweek) {
		this.timedayonweek = timedayonweek;
	}

}
