package model;
// Generated Aug 26, 2019 5:19:17 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name = "students", catalog = "qlsv", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Students implements java.io.Serializable {

	private Integer id;
	private Classes classes;
	private String name;
	private String code;
	private Integer age;
	private String address;
	private String phone;
	private String email;
	private String note;
	private Set<Registersub> registersubs = new HashSet<Registersub>(0);
	private Set<StudentsSubjects> studentsSubjectses = new HashSet<StudentsSubjects>(0);
	private Set<User> users = new HashSet<User>(0);

	public Students() {
	}

	public Students(Classes classes, String name, String code, Integer age, String address, String phone, String email,
			String note, Set<Registersub> registersubs, Set<StudentsSubjects> studentsSubjectses, Set<User> users) {
		this.classes = classes;
		this.name = name;
		this.code = code;
		this.age = age;
		this.address = address;
		this.phone = phone;
		this.email = email;
		this.note = note;
		this.registersubs = registersubs;
		this.studentsSubjectses = studentsSubjectses;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id")
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@Column(name = "name", length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", unique = true, length = 8)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "address", length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", length = 65535)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 65535)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	public Set<Registersub> getRegistersubs() {
		return this.registersubs;
	}

	public void setRegistersubs(Set<Registersub> registersubs) {
		this.registersubs = registersubs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	public Set<StudentsSubjects> getStudentsSubjectses() {
		return this.studentsSubjectses;
	}

	public void setStudentsSubjectses(Set<StudentsSubjects> studentsSubjectses) {
		this.studentsSubjectses = studentsSubjectses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "students")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
