package model;
// Generated Aug 26, 2019 5:19:17 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Subjects generated by hbm2java
 */
@Entity
@Table(name = "subjects", catalog = "qlsv", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Subjects implements java.io.Serializable {

	private Integer id;
	private String code;
	private Double coefficient;
	private String note;
	private String name;
	private Set<ClassSubject> classSubjects = new HashSet<ClassSubject>(0);

	public Subjects() {
	}

	public Subjects(String code, Double coefficient, String note, String name, Set<ClassSubject> classSubjects) {
		this.code = code;
		this.coefficient = coefficient;
		this.note = note;
		this.name = name;
		this.classSubjects = classSubjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, length = 6)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "coefficient", precision = 255, scale = 0)
	public Double getCoefficient() {
		return this.coefficient;
	}

	public void setCoefficient(Double coefficient) {
		this.coefficient = coefficient;
	}

	@Column(name = "note", length = 16777215)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "name", length = 16777215)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subjects")
	public Set<ClassSubject> getClassSubjects() {
		return this.classSubjects;
	}

	public void setClassSubjects(Set<ClassSubject> classSubjects) {
		this.classSubjects = classSubjects;
	}

}
