package model;
// Generated Aug 26, 2019 5:19:17 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Timedayonweek generated by hbm2java
 */
@Entity
@Table(name = "timedayonweek", catalog = "qlsv")
public class Timedayonweek implements java.io.Serializable {

	private Integer id;
	private String day;
	private Date startTime;
	private Date endTime;
	private Set<Registersub> registersubs = new HashSet<Registersub>(0);

	public Timedayonweek() {
	}

	public Timedayonweek(String day, Date startTime, Date endTime, Set<Registersub> registersubs) {
		this.day = day;
		this.startTime = startTime;
		this.endTime = endTime;
		this.registersubs = registersubs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "day", length = 65535)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "start_time", length = 16)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "end_time", length = 16)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timedayonweek")
	public Set<Registersub> getRegistersubs() {
		return this.registersubs;
	}

	public void setRegistersubs(Set<Registersub> registersubs) {
		this.registersubs = registersubs;
	}

}
